# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/work/gserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/work/gserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/work/gserver/CMakeFiles /home/ubuntu/work/gserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/work/gserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gserver-1.1.out

# Build rule for target.
gserver-1.1.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gserver-1.1.out
.PHONY : gserver-1.1.out

# fast build rule for target.
gserver-1.1.out/fast:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/build
.PHONY : gserver-1.1.out/fast

CompletionQue.o: CompletionQue.cpp.o

.PHONY : CompletionQue.o

# target to build an object file
CompletionQue.cpp.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/CompletionQue.cpp.o
.PHONY : CompletionQue.cpp.o

CompletionQue.i: CompletionQue.cpp.i

.PHONY : CompletionQue.i

# target to preprocess a source file
CompletionQue.cpp.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/CompletionQue.cpp.i
.PHONY : CompletionQue.cpp.i

CompletionQue.s: CompletionQue.cpp.s

.PHONY : CompletionQue.s

# target to generate assembly for a file
CompletionQue.cpp.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/CompletionQue.cpp.s
.PHONY : CompletionQue.cpp.s

LobbyProcess.o: LobbyProcess.cpp.o

.PHONY : LobbyProcess.o

# target to build an object file
LobbyProcess.cpp.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/LobbyProcess.cpp.o
.PHONY : LobbyProcess.cpp.o

LobbyProcess.i: LobbyProcess.cpp.i

.PHONY : LobbyProcess.i

# target to preprocess a source file
LobbyProcess.cpp.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/LobbyProcess.cpp.i
.PHONY : LobbyProcess.cpp.i

LobbyProcess.s: LobbyProcess.cpp.s

.PHONY : LobbyProcess.s

# target to generate assembly for a file
LobbyProcess.cpp.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/LobbyProcess.cpp.s
.PHONY : LobbyProcess.cpp.s

LoginProcess.o: LoginProcess.cpp.o

.PHONY : LoginProcess.o

# target to build an object file
LoginProcess.cpp.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/LoginProcess.cpp.o
.PHONY : LoginProcess.cpp.o

LoginProcess.i: LoginProcess.cpp.i

.PHONY : LoginProcess.i

# target to preprocess a source file
LoginProcess.cpp.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/LoginProcess.cpp.i
.PHONY : LoginProcess.cpp.i

LoginProcess.s: LoginProcess.cpp.s

.PHONY : LoginProcess.s

# target to generate assembly for a file
LoginProcess.cpp.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/LoginProcess.cpp.s
.PHONY : LoginProcess.cpp.s

PacketHandler.o: PacketHandler.cpp.o

.PHONY : PacketHandler.o

# target to build an object file
PacketHandler.cpp.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/PacketHandler.cpp.o
.PHONY : PacketHandler.cpp.o

PacketHandler.i: PacketHandler.cpp.i

.PHONY : PacketHandler.i

# target to preprocess a source file
PacketHandler.cpp.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/PacketHandler.cpp.i
.PHONY : PacketHandler.cpp.i

PacketHandler.s: PacketHandler.cpp.s

.PHONY : PacketHandler.s

# target to generate assembly for a file
PacketHandler.cpp.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/PacketHandler.cpp.s
.PHONY : PacketHandler.cpp.s

PacketProcessThread.o: PacketProcessThread.cpp.o

.PHONY : PacketProcessThread.o

# target to build an object file
PacketProcessThread.cpp.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/PacketProcessThread.cpp.o
.PHONY : PacketProcessThread.cpp.o

PacketProcessThread.i: PacketProcessThread.cpp.i

.PHONY : PacketProcessThread.i

# target to preprocess a source file
PacketProcessThread.cpp.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/PacketProcessThread.cpp.i
.PHONY : PacketProcessThread.cpp.i

PacketProcessThread.s: PacketProcessThread.cpp.s

.PHONY : PacketProcessThread.s

# target to generate assembly for a file
PacketProcessThread.cpp.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/PacketProcessThread.cpp.s
.PHONY : PacketProcessThread.cpp.s

Process.o: Process.cpp.o

.PHONY : Process.o

# target to build an object file
Process.cpp.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/Process.cpp.o
.PHONY : Process.cpp.o

Process.i: Process.cpp.i

.PHONY : Process.i

# target to preprocess a source file
Process.cpp.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/Process.cpp.i
.PHONY : Process.cpp.i

Process.s: Process.cpp.s

.PHONY : Process.s

# target to generate assembly for a file
Process.cpp.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/Process.cpp.s
.PHONY : Process.cpp.s

Server.o: Server.cpp.o

.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i

.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s

.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/Server.cpp.s
.PHONY : Server.cpp.s

TetrisProcess.o: TetrisProcess.cpp.o

.PHONY : TetrisProcess.o

# target to build an object file
TetrisProcess.cpp.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/TetrisProcess.cpp.o
.PHONY : TetrisProcess.cpp.o

TetrisProcess.i: TetrisProcess.cpp.i

.PHONY : TetrisProcess.i

# target to preprocess a source file
TetrisProcess.cpp.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/TetrisProcess.cpp.i
.PHONY : TetrisProcess.cpp.i

TetrisProcess.s: TetrisProcess.cpp.s

.PHONY : TetrisProcess.s

# target to generate assembly for a file
TetrisProcess.cpp.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/TetrisProcess.cpp.s
.PHONY : TetrisProcess.cpp.s

User.o: User.cpp.o

.PHONY : User.o

# target to build an object file
User.cpp.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/User.cpp.o
.PHONY : User.cpp.o

User.i: User.cpp.i

.PHONY : User.i

# target to preprocess a source file
User.cpp.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/User.cpp.i
.PHONY : User.cpp.i

User.s: User.cpp.s

.PHONY : User.s

# target to generate assembly for a file
User.cpp.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/User.cpp.s
.PHONY : User.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/main.cpp.s
.PHONY : main.cpp.s

msg.pb.o: msg.pb.cc.o

.PHONY : msg.pb.o

# target to build an object file
msg.pb.cc.o:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/msg.pb.cc.o
.PHONY : msg.pb.cc.o

msg.pb.i: msg.pb.cc.i

.PHONY : msg.pb.i

# target to preprocess a source file
msg.pb.cc.i:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/msg.pb.cc.i
.PHONY : msg.pb.cc.i

msg.pb.s: msg.pb.cc.s

.PHONY : msg.pb.s

# target to generate assembly for a file
msg.pb.cc.s:
	$(MAKE) -f CMakeFiles/gserver-1.1.out.dir/build.make CMakeFiles/gserver-1.1.out.dir/msg.pb.cc.s
.PHONY : msg.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... gserver-1.1.out"
	@echo "... edit_cache"
	@echo "... CompletionQue.o"
	@echo "... CompletionQue.i"
	@echo "... CompletionQue.s"
	@echo "... LobbyProcess.o"
	@echo "... LobbyProcess.i"
	@echo "... LobbyProcess.s"
	@echo "... LoginProcess.o"
	@echo "... LoginProcess.i"
	@echo "... LoginProcess.s"
	@echo "... PacketHandler.o"
	@echo "... PacketHandler.i"
	@echo "... PacketHandler.s"
	@echo "... PacketProcessThread.o"
	@echo "... PacketProcessThread.i"
	@echo "... PacketProcessThread.s"
	@echo "... Process.o"
	@echo "... Process.i"
	@echo "... Process.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... TetrisProcess.o"
	@echo "... TetrisProcess.i"
	@echo "... TetrisProcess.s"
	@echo "... User.o"
	@echo "... User.i"
	@echo "... User.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... msg.pb.o"
	@echo "... msg.pb.i"
	@echo "... msg.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

